### ISSUE TITLE
Document the limitations

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/static-site-fastly-deployer#6]
There are limits on how much can be stored in an edge dictionary.

> Dictionary containers, item keys, and their values have specific limits. Dictionary containers are limited to 1000 items. Dictionary item keys are limited to 256 characters and their values are limited to 8000 characters. If you find your dictionaries approaching these resource limits, contact us at support@fastly.com. We may be able to help you figure out more efficient ways to do things.

https://docs.fastly.com/guides/edge-dictionaries/about-edge-dictionaries#limitations-and-considerations

**Comment by JakeChampion** [comment]
We are not using Edge Dictionaries. We are using Snippets which have bigger size limits.
https://docs.fastly.com/vcl/vcl-snippets/about-vcl-snippets/#limitations-of-vcl-snippets

>Snippets are limited to 1MB in size by default. If you need to store snippets larger than the limit, contact support@fastly.com.

**Comment by JakeChampion** [comment]
The maximum limit on VCL snippets is 16MB

**Comment by JakeChampion** [comment]
Currently does not work with binary content, which means no Brotli or GZIP compression

**Comment by JakeChampion** [comment]
Currently missing support for returning 304 responses.

**Comment by JakeChampion** [comment]
How should it deal with request methods other than GET?

**Comment by JakeChampion** [comment]
Currently missing custom headers, we will follow the approach Netlify has taken with a file named `_headers` -- https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers

**Comment by JakeChampion** [comment]
Even with the 16MB hard size limit on snippets, overall maximum VCL size can only be 3MB right now. Which limits a website to only 3MB of content for their entire site.

**Comment by sjparkinson** [comment]
> How should it deal with request methods other than GET?

Respond with a 405 method not supported!

**Comment by JakeChampion** [comment]
> Currently does not work with binary content, which means no Brotli or GZIP compression

Binary synthetic responses are now supported via `synthetic.base64`.
